#!/usr/bin/env bash
#The second line of my Bash scripts is a comment explaining what it is doing
n=1

while [ $n -le 100 ]
do
	if [[ $((n%5)) -eq 0 && $((n%3)) -eq 0 ]]
	then
		printf "%s\n" "FizzBuzz"
		((n++))
	elif [[ $((n%3)) -eq 0 ]]
	then
		printf "%s\n" "Fizz"
		((n++))
	elif [[ $((n%5)) -eq 0 ]]
	then
		printf "%s\n" "Buzz"
		((n++))
	else
		printf "%s\n" "$n"
		((n++))
	fi
done
