#!/usr/bin/env bash
#The second line of my Bash scripts is a comment explaining what it is doing
PASSWD="/etc/passwd"

while IFS=: read -r username password userid groupid comment homedir cmdshell
	do
        echo "The user $username is part of $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
	done < $PASSWD
