#!/usr/bin/env bash
#The second line of my Bash scripts is a comment explaining what it is doing
n=1
while [ $n -le 10 ]
do   	
	if [ $n = 4 ] 
	then 
	echo "bad luck"
	printf "%s\n" "Best School"
	((n++))
	elif [ $n = 8 ] 
	echo "good luck"
	printf "%s\n" "Best School"
        ((n++))
	else
	printf "%s\n" "Best School"
        ((n++))
	fi
done

