#!/usr/bin/env bash
#The second line of my Bash scripts is a comment explaining what it is doing
n=1
while [ $n -le 20 ]
do
case $n in	
	4)  
	echo \n "bad luck from China"
	((n++))
	;;
        9)
	echo "bad luck from Japan"	
        ((n++))
	;;
        17)
	echo "bad luck from Italy"
        ((n++))
	;;
        *)
	echo "$n"
	((n++))
	       	

esac
done
