#!/usr/bin/env bash
#shell processes project
echo "$$" > /var/run/myscript.pid
while true
do
	echo  "To infinity and beyond"
done
trap "echo I hate the kill command; rm /var/run/myscript.pid; pkill -f /var/run/myscript.pid" SIGTERM
        trap "echo Y U no love me?!; exit" SIGINT
        trap " rm /var/run/myscript.pid; pkill -f /var/run/myscript.pid" SIGQUIT

